language: php

dist: trusty
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 7.3
      env: SHOPWARE_VERSION=\~5.6.3
    - php: 7.2
      env: SHOPWARE_VERSION=\~5.6.3
    - php: 7.2
      env: SHOPWARE_VERSION=\~5.5.10
    - php: 7.2
      env: SHOPWARE_VERSION=\~5.4.6
    - php: 7.2
      env: SHOPWARE_VERSION=\~5.3.7
    - php: 7.2
      env: SHOPWARE_VERSION=\~5.2.27
    - php: 7.1
      env: SHOPWARE_VERSION=\~5.5.10
    - php: 7.1
      env: SHOPWARE_VERSION=\~5.4.6
    - php: 7.1
      env: SHOPWARE_VERSION=\~5.3.7
    - php: 7.1
      env: SHOPWARE_VERSION=\~5.2.27
    - php: 7.0
      env: SHOPWARE_VERSION=\~5.5.10
    - php: 7.0
      env: SHOPWARE_VERSION=\~5.4.6
    - php: 7.0
      env: SHOPWARE_VERSION=\~5.3.7
    - php: 7.0
      env: SHOPWARE_VERSION=\~5.2.27

before_script:
  - ./etc/scripts/prepareComposerJson.sh
  - composer update -n --no-progress --no-suggest

script:
  - if ( [ "${TRAVIS_PHP_VERSION}" == "7.3" ] && [ "${SHOPWARE_VERSION}" == "\~5.6.3" ] ); then ./etc/scripts/checkCodingStandards.sh; fi
  - vendor/bin/phpspec-standalone.php${TRAVIS_PHP_VERSION}.phar run --no-code-generation --format=dot
  - vendor/bin/phpunit -c phpunit_unit.xml.dist
  - ./etc/scripts/checkForCorrectPluginStructure.sh
